### PR TITLE
Resize view when keyboard appears to prevent hiding text

### PR DESCRIPTION
**Pull request by alessionossa**
The view now updates its insets when the keyboard appears/disappears so that you can see the whole file.

### CODE REVIEW

**Comment by twostraws** [comment]
Hello! Thank you for your contribution. You're putting several changes into one PR, which makes it hard to review. I don't think the text view ought to resize when the keyboard appears – Apple's own `UITextView` doesn't. As for the extra lexer, that is most welcome!

**Comment by alessionossa** [comment]
Sorry for the multiple changes in a single PR. 

Apple `UITextView` doesn’t resize itself when you place it in a full screen view in your app, but if a user try to write more than ~20 lines in that textview, the text will be hidden by the keyboard and the last lines will not be visible until the user dismiss the keyboard. The same problem was happening with the `SyntaxTextView`.

**Comment by twostraws** [comment]
Right, and I expect folks to solve this the same way it's solved in `UITextView`: they adjust the bounds by hand.

**Comment by alessionossa** [comment]
Okay, that’s a good idea. I'll close this pull request and probably make one only for the Shell Lexer.
I also created a sample project on a new branch, that showcase Sourceful in a very simple SwiftUI project ( https://github.com/alessionossa/Sourceful/tree/sample ). Do you think it can be useful to add to this repo?

**Comment by twostraws** [comment]
I think a sample project would be most welcome. Is it possible to add the same thing in UIKit?

**Pull request closed without merging**
