### PR TITLE
fix #25 . Don't update state if the text hasn't changed.

### LINKED ISSUE #25: insertion point goes to the end after editing (SwiftUI, macOS)
Each time I enter a character in the SourceCodeTextEditor, the insertion point goes to the end.

Assuming this is a bug in Sourceful, since if I replace SourceCodeTextEditor with TextEditor, the insertion point doesn't jump.

I'll dig deeper into this.

### PR DESCRIPTION
**Pull request by wtholliday**
Pretty simple fix.

### CODE REVIEW

**Comment by shredsonic** [comment]
What issue does this fix? Under what circumstances are you seeing the text being updated when it hasn't changed?

**Comment by shredsonic** [comment]
Ah I see now. If you put the fix # issue in the description instead of the title, then this will actually close the issue when it's merged in. Im not sure if it works in the title and also it doesn't provide a hyperlink to the issue.

**Comment by wtholliday** [comment]
Ah darn I didn't want that last commit to be part of this PR. I'll probably make a separate branch and submit a new PR.

**Comment by wtholliday** [comment]
Will submit a cleaned up PR later.

**Pull request closed without merging**
